# Generated by Django 2.0.13 on 2019-07-18 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
